# A generic, single database configuration.

[alembic]
# Ruta al directorio de migraciones
script_location = alembic

# Agrega el directorio backend al sys.path (para importar app.*)
prepend_sys_path = .

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# URL se configura en alebic/env.py desde app.config.settings
# sqlalchemy.url =

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S